### ISSUE TITLE
On updating employment details , getting error message " Joined at can't be blank" 

### ISSUE THREAD

**Issue by supriya3105** [saeloun/miru-web#1486] opened 2023-09-26 07:44 UTC
### Description

On updating employment details , getting error message " Joined at can't be blank"  even though the date of joining field is not blank. 

### Environment

    Linux / MacOS / Android / IOS / Windows
    Mozilla / Chrome / Safari

### What is the expected behaviour?

The error message "Joined at can't be blank should not be displayed. 

### What is the current behaviour?

Toast error message is displayed "Joined at can't be blank"

### How to reproduce the issue?

1. Login as any user i.e. admin/owner/employee
2. Go to settings 
3. Click on employment details tab 
4. Click on edit button 
5. Click on Update button 

### Screenshots or Screencast

<img width="1440" alt="Screenshot 2023-09-26 at 1 07 12 PM" src="https://github.com/saeloun/miru-web/assets/91338424/82e64ba1-c41e-4901-8889-473fdc555e26">

**Comment by charann29** [comment] 2023-09-28 12:24
@supriya3105 I'm interested in working on this issue. Could you please assign it to me?  I'll start investigating the problem and work on a potential solution. Thank you!

**Comment by supriya3105** [comment] 2023-09-28 14:29
@charann29 Assigned the bug to you.

**Comment by apoorv1316** [comment] 2023-10-03 05:21
@charann29 Were you able to start working on the issue? Feel free to ask for help if you are stuck.

**Comment by apoorv1316** [comment] 2023-10-11 07:02
@charann29 Any update on the issue?

**Comment by luansmartr** [comment] 2023-10-12 12:45
Can i work on this issue?

**Comment by apoorv1316** [comment] 2023-10-13 04:40
@luansmartr Assigned it you. Please join discord server and ping there if you need any help https://discord.gg/UhW7ssnQ

**Comment by luansmartr** [comment] 2023-10-13 06:57
Thank @apoorv1316

**Comment by apoorv1316** [comment] 2023-10-17 17:40
@luansmartr Have you started working on the issue? Feel free to ask help.

**Comment by apoorv1316** [comment] 2023-10-24 04:09
@luansmartr Are you working on this issue?

**Comment by sainikhil1605** [comment] 2023-10-26 14:34
Hi @apoorv1316 @supriya3105  I am unable to reproduce this issue on my local machine. 

https://github.com/saeloun/miru-web/assets/35322884/bb61ac4e-85d1-4bfa-b845-bb590e9d8244

**Closed** 2023-12-13 10:51 UTC
Labels: bug
