### ISSUE TITLE
The teams page is displaying the client users as well 

### ISSUE THREAD

**Issue by supriya3105** [saeloun/miru-web#1782] opened 2024-04-03 10:20 UTC
### Description

The teams page lists the client users as well. 

### What is the expected behaviour?

As per the functionality, on the teams page the users with the role as admin, reviewer and bookkeeper should be displayed. 

### What is the current behaviour?

The teams page lists the client users as well. 

### How to reproduce the issue?

1.login as admin/owner user 
2. Navigate to the team page.

### Screenshots or Screencast

<img width="1440" alt="Screenshot 2024-04-03 at 3 45 35 PM" src="https://github.com/saeloun/miru-web/assets/91338424/18e06018-b30f-4869-8eab-cb1b2e9bcdc0">

**Comment by sonamvg** [comment] 2024-04-04 08:35
This is the duplicate issue of the existing bug. Please confirm with Nishant regarding this.

**Comment by nisusam** [comment] 2024-04-04 09:49
Duplicate of https://github.com/saeloun/miru-web/issues/1775, hence closing the same.

**Closed by nisusam** 2024-04-04 09:49 UTC
Labels: bug
